export const DEFAULT_SCENE_PARAMS = {
    elevation: 15.6,
    azimuth: -180,
    exposure: 0,
    turbidity: 2.7,
    rayleigh: 4.0,
    bloomStrength: 0,
    bloomRadius: 0,
    bloomThreshold: 0,
    waterColor: '#18465a',
    cloudCoverage: 0.46,
    cloudDensity: 0.38,
    cloudAtmosphereStrength: 0.68,
    cloudAbsorptionStrength: 0.82,
    cloudShadowStrength: 0.28,
    cloudBaseHeight: 25000,
    cloudTopHeight: 30000,
    cloudElevation: 0.66,
    fogEnabled: false,
    fogDensity: 0.16,
    fogHeight: 0.26,
    fogRange: 0.38,
    rainEnabled: false,
    rainScreenIntensity: 0.41,
    rainVeilIntensity: 1.15,
    rainDropSize: 1.0,
    rainSpeed: 1.0,
    rainAudioEnabled: true,
    rainAudioVolume: 0.35,
    snowEnabled: false,
    snowIntensity: 0.65,
    snowSpeed: 0.85,
    starEnabled: true,
    starIntensity: 0.7,
    lightningEnabled: true,
    lightningIntensity: 0.75,
    thunderVolume: 1.0,
    mieCoefficient: 0.005,
    mieDirectionalG: 0.8
};

export const WEATHER_PRESETS = {
    default: {
        label: '夕阳',
        params: {
            ...DEFAULT_SCENE_PARAMS
        }
    },
    clear: {
        label: '日出',
        params: {
            ...DEFAULT_SCENE_PARAMS,
            elevation: 2.5,
            azimuth: 0,
            exposure: 0.28,
            turbidity: 1.0,
            rayleigh: 2.18,
            bloomStrength: 0.22,
            bloomRadius: 0.38,
            waterColor: '#2d6f74',
            cloudCoverage: 0.34,
            cloudDensity: 0.24,
            cloudBaseHeight: 3800,
            cloudTopHeight: 8500,
            cloudElevation: 0.9,
            fogDensity: 0.12,
            fogHeight: 0.58,
            fogRange: 0.28,
            starIntensity: 0.22,
            lightningEnabled: false
        }
    },
    noon: {
        label: '正午',
        params: {
            ...DEFAULT_SCENE_PARAMS,
            elevation: 72,
            azimuth: 180,
            exposure: 0.45,
            turbidity: 2.2,
            rayleigh: 0.18,
            bloomStrength: 0.2,
            bloomRadius: 0.03,
            waterColor: '#25b7d9',
            cloudCoverage: 0.06,
            cloudDensity: 0.12,
            cloudBaseHeight: 4500,
            cloudTopHeight: 9500,
            cloudElevation: 0.82,
            fogDensity: 0.015,
            fogHeight: 0.12,
            fogRange: 0.08,
            starIntensity: 0.0,
            lightningEnabled: false
        }
    },
    night: {
        label: '黑夜',
        params: {
            ...DEFAULT_SCENE_PARAMS,
            elevation: -8,
            azimuth: 205,
            exposure: 0.2,
            turbidity: 1.8,
            rayleigh: 0.2,
            bloomStrength: 0.12,
            bloomRadius: 0.08,
            waterColor: '#07131f',
            cloudCoverage: 0.03,
            cloudDensity: 0.08,
            cloudBaseHeight: 5200,
            cloudTopHeight: 11000,
            cloudElevation: 0.78,
            fogDensity: 0.08,
            fogHeight: 0.22,
            fogRange: 0.2,
            rainEnabled: false,
            snowEnabled: false,
            starEnabled: true,
            starIntensity: 0.4,
            lightningEnabled: false
        }
    },
    overcast: {
        label: '阴天',
        params: {
            ...DEFAULT_SCENE_PARAMS,
            elevation: 24,
            azimuth: 168,
            exposure: 0.11,
            turbidity: 15.8,
            rayleigh: 1.2,
            bloomStrength: 0.08,
            bloomRadius: 0.18,
            waterColor: '#315565',
            cloudCoverage: 0.84,
            cloudDensity: 0.88,
            cloudBaseHeight: 3200,
            cloudTopHeight: 7500,
            cloudElevation: 0.34,
            fogDensity: 0.38,
            fogHeight: 0.36,
            fogRange: 0.62,
            starIntensity: 0.04,
            lightningEnabled: false
        }
    },
    rainy: {
        label: '下雨',
        params: {
            ...DEFAULT_SCENE_PARAMS,
            elevation: 45,
            azimuth: 170,
            exposure: 0.085,
            turbidity: 3.5,
            rayleigh: 0,
            bloomStrength: 0,
            bloomRadius: 0,
            waterColor: '#223d48',
            cloudCoverage: 0.48,
            cloudDensity: 0.92,
            cloudBaseHeight: 2800,
            cloudTopHeight: 8000,
            cloudElevation: 0.82,
            fogDensity: 0.62,
            fogHeight: 0.34,
            fogRange: 0.78,
            rainEnabled: true,
            rainScreenIntensity: 0.38,
            rainVeilIntensity: 1.4,
            rainDropSize: 0.4,
            rainSpeed: 1.16,
            rainAudioEnabled: true,
            rainAudioVolume: 0.38,
            starIntensity: 0.02,
            lightningEnabled: true,
            lightningIntensity: 0.68,
            snowEnabled: false
        }
    },
    snow: {
        label: '降雪',
        params: {
            ...DEFAULT_SCENE_PARAMS,
            elevation: 20,
            azimuth: 172,
            exposure: 0.1,
            turbidity: 14.5,
            rayleigh: 1.4,
            bloomStrength: 0.06,
            bloomRadius: 0.12,
            waterColor: '#355160',
            cloudCoverage: 0.88,
            cloudDensity: 0.76,
            cloudBaseHeight: 2500,
            cloudTopHeight: 7200,
            cloudElevation: 0.38,
            fogDensity: 0.56,
            fogHeight: 0.42,
            fogRange: 0.74,
            starIntensity: 0.16,
            rainEnabled: false,
            lightningEnabled: false,
            snowEnabled: true,
            snowIntensity: 1.18,
            snowSpeed: 1.28
        }
    }
};
